window.version_kiosk = {
    region: "NDPE",
    name: "Kiosk",
    table_offset: 1,
    geo_offset: 8,
    pointer_offset: 0x1A7C20,
    fluids: [
        {
            texture: {
                index: 0x3E1,
                table: 7,
                width: 32,
                height: 32,
            },
            ripple: 0, // field_0x14[1]
            name: "0: Water",
            loader: window.texParserRGBA32,
        },
        {
            texture: {
                index: 0x30D,
                table: 25,
                width: 64,
                height: 64,
            },
            palette: {
                index: 0x30E,
                table: 25,
                width: 4,
                height: 4,
            },
            ripple: 0,
            name: "1: Deep Lava",
            loader: window.texParserCI4,
        },
        {
            texture: {
                index: 0x14F,
                table: 25,
                width: 32,
                height: 32,
            },
            ripple: 1,
            name: "2: Japes Dillo Ground",
            loader: window.texParserRGBA5551,
        },
        {
            texture: {
                index: 0x3E1,
                table: 7,
                width: 32,
                height: 32,
            },
            ripple: 0,
            name: "3: Water",
            loader: window.texParserRGBA32,
        },
        {
            texture: {
                index: 0x7C0,
                table: 25,
                width: 32,
                height: 32,
            },
            ripple: 2,
            name: "4: Caves Dillo Ground",
            loader: window.texParserRGBA5551,
        },
        {
            texture: {
                index: 0x3DD,
                table: 7,
                width: 32,
                height: 32,
            },
            ripple: 0,
            name: "5: Lava",
            loader: window.texParserRGBA5551,
        },
        {
            texture: {
                index: 0x3EE,
                table: 7,
                width: 32,
                height: 32,
            },
            ripple: 0,
            name: "6: Acid",
            loader: window.texParserRGBA5551,
        },
        {
            texture: {
                index: 0x3EF, // Also loads 0x3DB?
                table: 7,
                width: 32,
                height: 32,
            },
            ripple: 0,
            name: "7: Water Lava",
            loader: window.texParserRGBA5551,
        },
    ],
    overlay_data: [
        {},
        {
            compressed: false,
            rom_code_start: 0x14B0,
            rom_data_end: 0x14B0 + 0x17C470,
            rdram_start: 0x805904B0
        },
        {},
        {},
        {
            compressed: false,
            rom_code_start: 0x17D920,
            rom_data_end: 0x17D920 + 0x4F80,
            rdram_start: 0x80000400,
        },
        {
            compressed: false,
            rom_code_start: 0x18D150,
            rom_data_end: 0x18D150 + 0xBD70,
            rdram_start: 0x80000400,
        },
        {
            compressed: false,
            rom_code_start: 0x198EC0,
            rom_data_end: 0x198EC0 + 0x46C0,
            rdram_start: 0x80000400,
        },
        {
            compressed: false,
            rom_code_start: 0x19D580,
            rom_data_end: 0x19D580 + 0x9590,
            rdram_start: 0x80000400,
        },
        {
            compressed: false,
            rom_code_start: 0x1828A0,
            rom_data_end: 0x1828A0 + 0xA8B0,
            rdram_start: 0x80000400,
        },
        {},
        {},
        {
            compressed: false,
            rom_code_start: 0x1A6B10,
            rom_data_end: 0x1A6B10 + 0xF00,
            rdram_start: 0x80000400,
        },
    ],
    actor_behav_rdram: 0x806F9F80,
    actor_behav_count: 109,
    actor_spawner_offset: 0xF,
    char_spawner_rdram: 0x8070A460,
    char_spawner_count: 103,
    char_spawner_size: 0x1C,
    cutscene_model_rdram: 0x807001F0,
    cutscene_model_count: 28,
    sprite_table: 0x806FFEC0,
    actor_sprites: [
        { actor: 113, sprite_index: 142 },
        { actor: 90, sprite_index: 141 },
        { actor: 112, sprite_index: 143 },
        { actor: 111, sprite_index: 144 },
        { actor: 110, sprite_index: 140 },
    ],
    balloons: [113, 90, 112, 111, 110],
    has_box_void: false,
    music_triggers: [
        { map_id: 0x07, count: 7, addr: 0x806F31A0 },
        { map_id: 0x26, count: 4, addr: 0x806F3204 },
        { map_id: 0x1E, count: 4, addr: 0x806F323C },
        { map_id: 0x27, count: 4, addr: 0x806F3274 },
        { map_id: 0x1A, count: 3, addr: 0x806F32AC },
        { map_id: 0x0E, count: 4, addr: 0x806F32D8 },
        { map_id: 0x1B, count: 10, addr: 0x806F3310 },
        { map_id: 0x30, count: 1, addr: 0x806F339C },
        { map_id: 0x37, count: 7, addr: 0x806F33AC },
        { map_id: 0x99, count: 4, addr: 0x806F3410 },
    ],
    distant_screen_texture: 0x3E3,
    amb_sfx: {
        offset: 0x806F2E48,
        count: 7,
        size: 0x8,
    }
}