const map_ids = {
    "Japes": {
        "Jungle Japes: Mountain": 4,
        "Jungle Japes: Minecart": 6,
        "Jungle Japes": 7,
        "Jungle Japes: Army Dillo": 8,
        "Jungle Japes: Shell": 12,
        "Jungle Japes: Lanky's Cave": 13,
        "Jungle Japes: Chunky's Cave": 33,
        "Jungle Japes: Barrel Blast": 37,
    },
    "Aztec": {
        "Angry Aztec: Beetle Race": 14,
        "Angry Aztec: Tiny's Temple": 16,
        "Angry Aztec: Five Door Temple (DK)": 19,
        "Angry Aztec: Llama Temple": 20,
        "Angry Aztec: Five Door Temple (Diddy)": 21,
        "Angry Aztec: Five Door Temple (Tiny)": 22,
        "Angry Aztec: Five Door Temple (Lanky)": 23,
        "Angry Aztec: Five Door Temple (Chunky)": 24,
        "Angry Aztec": 38,
        "Angry Aztec: Barrel Blast": 41,
        "Angry Aztec: Dogadon": 197,
    },
    "Factory": {
        "Frantic Factory": 26,
        "Frantic Factory: Barrel Blast": 110,
        "Frantic Factory: Car Race": 27,
        "Frantic Factory: Power Shed": 29,
        "Frantic Factory: Crusher Room": 36,
        "Frantic Factory: Mad Jack": 154,
    },
    "Galleon": {
        "Gloomy Galleon": 30,
        "Gloomy Galleon: K. Rool's Ship": 31,
        "Gloomy Galleon: Seal Race": 39,
        "Gloomy Galleon: Shipwreck (Diddy, Lanky, Chunky)": 43,
        "Gloomy Galleon: Treasure Chest": 44,
        "Gloomy Galleon: Mermaid": 45,
        "Gloomy Galleon: Shipwreck (DK, Tiny)": 46,
        "Gloomy Galleon: Shipwreck (Lanky, Tiny)": 47,
        "Gloomy Galleon: Lighthouse": 49,
        "Gloomy Galleon: Mechanical Fish": 51,
        "Gloomy Galleon: Barrel Blast": 54,
        "Gloomy Galleon: Submarine": 179,
        "Gloomy Galleon: Pufftoss": 111,
    },
    "Fungi": {
        "Fungi Forest": 48,
        "Fungi Forest: Ant Hill": 52,
        "Fungi Forest: Minecart": 55,
        "Fungi Forest: Diddy's Barn": 56,
        "Fungi Forest: Diddy's Attic": 57,
        "Fungi Forest: Lanky's Attic": 58,
        "Fungi Forest: DK's Barn": 59,
        "Fungi Forest: Spider": 60,
        "Fungi Forest: Front Part of Mill": 61,
        "Fungi Forest: Rear Part of Mill": 62,
        "Fungi Forest: Mushroom Puzzle": 63,
        "Fungi Forest: Giant Mushroom": 64,
        "Fungi Forest: Mushroom Leap": 70,
        "Fungi Forest: Shooting Game": 71,
        "Fungi Forest: Dogadon": 83,
        "Fungi Forest: Barrel Blast": 188,
    },
    "Caves": {
        "Crystal Caves": 72,
        "Crystal Caves: Beetle Race": 82,
        "Crystal Caves: Igloo (Tiny)": 84,
        "Crystal Caves: Igloo (Lanky)": 85,
        "Crystal Caves: Igloo (DK)": 86,
        "Crystal Caves: Rotating Room": 89,
        "Crystal Caves: Shack (Chunky)": 90,
        "Crystal Caves: Shack (DK)": 91,
        "Crystal Caves: Shack (Diddy, middle part)": 92,
        "Crystal Caves: Shack (Tiny)": 93,
        "Crystal Caves: Lanky's Hut": 94,
        "Crystal Caves: Igloo (Chunky)": 95,
        "Crystal Caves: Ice Castle": 98,
        "Crystal Caves: Igloo (Diddy)": 100,
        "Crystal Caves: Barrel Blast": 186,
        "Crystal Caves: Army Dillo": 196,
        "Crystal Caves: Shack (Diddy, upper part)": 200,
    },
    "Castle": {
        "Creepy Castle": 87,
        "Creepy Castle: Ballroom": 88,
        "Creepy Castle: Tower": 105,
        "Creepy Castle: Minecart": 106,
        "Creepy Castle: Crypt (Lanky, Tiny)": 108,
        "Creepy Castle: Crypt (DK, Diddy, Chunky)": 112,
        "Creepy Castle: Museum": 113,
        "Creepy Castle: Library": 114,
        "Creepy Castle: Dungeon": 151,
        "Creepy Castle: Chunky's Toolshed": 166,
        "Creepy Castle: Trash Can": 167,
        "Creepy Castle: Greenhouse": 168,
        "Creepy Castle: Basement": 163,
        "Creepy Castle: Tree": 164,
        "Creepy Castle: Crypt": 183,
        "Creepy Castle: Car Race": 185,
        "Creepy Castle: Barrel Blast": 187,
        "Creepy Castle: King Kut Out": 199,
    },
    "Helm & K Rool": {
        "Hideout Helm": 17,
        "Hideout Helm (Level Intros, Game Over)": 28,
        "K. Rool Fight: DK Phase": 203,
        "K. Rool Fight: Diddy Phase": 204,
        "K. Rool Fight: Lanky Phase": 205,
        "K. Rool Fight: Tiny Phase": 206,
        "K. Rool Fight: Chunky Phase": 207,
        "K. Lumsy Ending": 213,
        "K. Rool's Shoe": 214,
        "K. Rool's Arena": 215,
        "Hideout Helm (Intro Story)": 152,
    },
    "Isles": {
        "DK Isles Overworld": 34,
        "K. Lumsy": 97,
        "Jungle Japes Lobby": 169,
        "Angry Aztec Lobby": 173,
        "Frantic Factory Lobby": 175,
        "Gloomy Galleon Lobby": 174,
        "Fungi Forest Lobby": 178,
        "Crystal Caves Lobby": 194,
        "Creepy Castle Lobby": 193,
        "Hideout Helm Lobby": 170,
        "DK's House": 171,
        "Training Grounds": 176,
        "Training Grounds (End Sequence)": 198,
        "DK Isles (DK Theatre)": 153,
        "Rock (Intro Story)": 172,
        "Fairy Island": 189,
        "DK Isles: Snide's Room": 195,
    },
    "Minigames": {
        "K. Rool Barrel: Lanky's Maze": 3,
        "Kremling Kosh! (very easy)": 10,
        "Stealthy Snoop! (normal, no logo)": 11,
        "Teetering Turtle Trouble! (very easy)": 18,
        "Batty Barrel Bandit! (easy)": 32,
        "K. Rool Barrel: DK's Target Game": 35,
        "K. Rool Barrel: Tiny's Mushroom Game": 50,
        "Stealthy Snoop! (normal)": 65,
        "Mad Maze Maul! (hard)": 66,
        "Stash Snatch! (normal)": 67,
        "Mad Maze Maul! (easy)": 68,
        "Mad Maze Maul! (normal)": 69,
        "Stash Snatch! (easy)": 74,
        "Stash Snatch! (hard)": 75,
        "Minecart Mayhem! (easy)": 77,
        "Busy Barrel Barrage! (easy)": 78,
        "Busy Barrel Barrage! (normal)": 79,
        "Splish-Splash Salvage! (normal)": 96,
        "Speedy Swing Sortie! (easy)": 99,
        "Krazy Kong Klamour! (easy)": 101,
        "Big Bug Bash! (very easy)": 102,
        "Searchlight Seek! (very easy)": 103,
        "Beaver Bother! (easy)": 104,
        "Kremling Kosh! (easy)": 115,
        "Kremling Kosh! (normal)": 116,
        "Kremling Kosh! (hard)": 117,
        "Teetering Turtle Trouble! (easy)": 118,
        "Teetering Turtle Trouble! (normal)": 119,
        "Teetering Turtle Trouble! (hard)": 120,
        "Batty Barrel Bandit! (easy)": 121,
        "Batty Barrel Bandit! (normal)": 122,
        "Batty Barrel Bandit! (hard)": 123,
        "Mad Maze Maul! (insane)": 124,
        "Stash Snatch! (insane)": 125,
        "Stealthy Snoop! (very easy)": 126,
        "Stealthy Snoop! (easy)": 127,
        "Stealthy Snoop! (hard)": 128,
        "Minecart Mayhem! (normal)": 129,
        "Minecart Mayhem! (hard)": 130,
        "Busy Barrel Barrage! (hard)": 131,
        "Splish-Splash Salvage! (hard)": 132,
        "Splish-Splash Salvage! (easy)": 133,
        "Speedy Swing Sortie! (normal)": 134,
        "Speedy Swing Sortie! (hard)": 135,
        "Beaver Bother! (normal)": 136,
        "Beaver Bother! (hard)": 137,
        "Searchlight Seek! (easy)": 138,
        "Searchlight Seek! (normal)": 139,
        "Searchlight Seek! (hard)": 140,
        "Krazy Kong Klamour! (normal)": 141,
        "Krazy Kong Klamour! (hard)": 142,
        "Krazy Kong Klamour! (insane)": 143,
        "Peril Path Panic! (very easy)": 144,
        "Peril Path Panic! (easy)": 145,
        "Peril Path Panic! (normal)": 146,
        "Peril Path Panic! (hard)": 147,
        "Big Bug Bash! (easy)": 148,
        "Big Bug Bash! (normal)": 149,
        "Big Bug Bash! (hard)": 150,
        "K. Rool Barrel: Diddy's Rocketbarrel Game": 201,
        "K. Rool Barrel: Lanky's Shooting Game": 202,
        "K. Rool Barrel: Chunky's Hidden Kremling Game": 209,
        "K. Rool Barrel: Tiny's Pony Tail Twirl Game": 210,
        "K. Rool Barrel: Chunky's Shooting Game": 211,
        "K. Rool Barrel: DK's Rambi Game": 212,
        "K. Rool Barrel: Diddy's Kremling Game": 165,
        "Dive Barrel": 177,
        "Orange Barrel": 180,
        "Barrel Barrel": 181,
        "Vine Barrel": 182,
        "Enguarde Arena": 184,
        "Rambi Arena": 191,
    },
    "Battle Arenas": {
        "Battle Arena: Beaver Brawl!": 53,
        "Battle Arena: Kritter Karnage!": 73,
        "Battle Arena: Arena Ambush!": 155,
        "Battle Arena: More Kritter Karnage!": 156,
        "Battle Arena: Forest Fracas!": 157,
        "Battle Arena: Bish Bash Brawl!": 158,
        "Battle Arena: Kamikaze Kremlings!": 159,
        "Battle Arena: Plinth Panic!": 160,
        "Battle Arena: Pinnacle Palaver!": 161,
        "Battle Arena: Shockwave Showdown!": 162,
    },
    "Misc": {
        "Test Map": 0,
        "Funky's Store": 1,
        "DK Arcade": 2,
        "Cranky's Lab": 5,
        "Jetpac": 9,
        "Snide's H.Q.": 15,
        "Candy's Music Shop": 25,
        "Nintendo Logo": 40,
        "Troff 'n' Scoff": 42,
        "DK Rap": 76,
        "Main Menu": 80,
        "Title Screen (Not For Resale Version)": 81,
        "Kong Battle: Arena 1": 109,
        "Kong Battle: Battle Arena": 107,
        "Kong Battle: Arena 2": 190,
        "Kong Battle: Arena 3": 192,
        "Bloopers Ending": 208,
    },
}

const geometries = {
    "Collision": "collision",
    "Collision (Walls)": "walls",
    "Collision (Floor Properties)": "floors",
    "Collision (Slippable Floors)": "slip",
    "Collision (Floor Special)": "enum_floors",
    "Level Geometry (Vertex Colors)": "geo",
}

const markers = [
    "Triggers",
    "Autowalks",
    "Paths",
    "Exits",
]

document.getElementById("map_id_selector").innerHTML = Object.keys(map_ids).map(group => {
    return `<optgroup label="${group}">${Object.keys(map_ids[group]).sort().map(map_name => {
        return `<option value="${map_ids[group][map_name]}">${map_name}</option>`
    }).join("")}</optgroup>`
}).join("");
document.getElementById("bg_selector").innerHTML = Object.keys(geometries).map(name => {
    return `<option value="${geometries[name]}">${name}</option>`
}).join("");

// Dropdowns
document.getElementById("map_id_selector").addEventListener("change", () => {
    window.renderHandler(true);
    window.renderHandler(false);
});
document.getElementById("bg_selector").addEventListener("change", () => {
    window.renderHandler(false);
});

// Toggles
document.getElementById("wf_selector").addEventListener("click", () => {
    window.renderHandler(false);
});
document.getElementById("trigger_selector").addEventListener("click", () => {
    window.renderHandler(false);
});
document.getElementById("lock_selector").addEventListener("click", () => {
    window.renderHandler(false);
});

// File Upload
document.getElementById("fileUploadButton").addEventListener("click", () => {
    document.getElementById("fileInput").click();
})